
version: "3.1"
services:
  db:
    container_name: sql-support_bot_db
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_NAME=support_bot_db
      - HOST='localhost'
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=111111
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./sql_conf:/etc/mysql/conf.d
