
CREATE DATABASE ${MYSQL_NAME};
CREATE USER ${MYSQL_USER}@${HOST} IDENTIFIED WITH mysql_native_password BY ${MYSQL_PASSWORD};
GRANT ALL ON ${MYSQL_NAME}.* TO ${MYSQL_USER}@${HOST};

FLUSH PRIVILEGES;

USE ${MYSQL_NAME};
