CREATE DATABASE support_bot_db;
CREATE USER 'bot'@'%' IDENTIFIED WITH mysql_native_password BY '123';
GRANT ALL ON support_bot_db.* TO 'bot'@'%';

FLUSH PRIVILEGES;

USE support_bot_db;

CREATE TABLE IF NOT EXISTS agents(id INT NOT NULL AUTO_INCREMENT, `agent_id` VARCHAR(20), PRIMARY KEY (id));
ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS passwords(id INT NOT NULL AUTO_INCREMENT, `password` VARCHAR(20), PRIMARY KEY (id));
ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS files(id INT NOT NULL AUTO_INCREMENT, `req_id` VARCHAR(20), `file_id` VARCHAR(250), `file_name` VARCHAR(2048), `type` VARCHAR(20), PRIMARY KEY (id));
ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS requests(req_id INT NOT NULL AUTO_INCREMENT, `user_id` VARCHAR(20), `req_status` VARCHAR(20), PRIMARY KEY (req_id));
ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS messages(id INT NOT NULL AUTO_INCREMENT, `req_id` VARCHAR(20), `message` VARCHAR(4096), `user_status` VARCHAR(20), `date` VARCHAR(50), PRIMARY KEY (id));
ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4;

/*CREATE DATABASE ${MYSQL_NAME};
CREATE USER ${MYSQL_USER}@${HOST} IDENTIFIED WITH mysql_native_password BY ${MYSQL_PASSWORD};
GRANT ALL ON ${MYSQL_NAME}.* TO ${MYSQL_USER}@${HOST};

/* Make sure the privileges are installed */
FLUSH PRIVILEGES;

USE ${MYSQL_NAME};*/
