
version: '3.7'
services:
 db:
    container_name: sql-support_bot_db
    image: mysql:8.0
    restart: always
    ports:
      - 3300:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../SQL-DB/sql:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
      - ../SQL-DB/sql_conf:/etc/mysql/conf.d
 telegram-bot-api:
    image: python:latest
    restart: always
    build: .
    depends_on:
     - db
    environment:
     - MYSQL_NAME=${MYSQL_NAME}
     - HOST=${HOST}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - TOKEN=${TOKEN}
     - ADMIN_ID=${ADMIN_ID}
    links:
     - db
    ports:
     - 8081:8081
    volumes:
        - ../:/data
volumes:
  db:
    driver: local

